#!/bin/sh

bright=$(brightnessctl get)
bright=$(echo "$bright" | awk '{print ($0 / 75)}')

notify-send -t 3000 -a 'notify-bright' -h string:x-canonical-private-synchronous:bright -h int:value:$bright "Bright: ${bright}"
