#!/usr/bin/sh

wpgvol=$(wpctl get-volume @DEFAULT_SINK@)
read vol flgmute_vol <<< $(echo $wpgvol \
    | awk '{ printf("%d %s", $2 * 100, $3 ? "MUTE" : "") }')

strvol="$vol${flgmute_vol:+ $flgmute_vol}"

notify-send -t 3000 -a 'notify-volume' \
    -h string:x-canonical-private-synchronous:volume \
    -h int:value:$vol \
    "Volume: $strvol"
