# https://fishshell.com/docs/current/interactive.html#syntax-highlighting-variables
fish_color_normal e0def4
fish_color_command ebbcba
fish_color_keyword ebbcba
fish_color_quote f6c177
fish_color_redirection
fish_color_end 9ccfd8
fish_color_error eb6f92
fish_color_param c4a7e7
fish_color_valid_path
fish_color_option --italics ebbcba
fish_color_comment --italics
fish_color_selection
fish_color_operator f6c177
fish_color_escape 6e6a86
fish_color_autosuggestion 524f67
fish_color_cwd --bold --dim
fish_color_cwd_root --bold --dim
fish_color_user f6c177
fish_color_host 31748f
fish_color_host_remote --reverse
fish_color_status eb6f92
fish_color_cancel --dim
fish_color_search_match --background 393552
fish_color_history_current --bold

# https://fishshell.com/docs/current/interactive.html#pager-color-variables
fish_pager_color_progress ebbcba
fish_pager_color_background 393552
fish_pager_color_prefix
fish_pager_color_completion 908caa
fish_pager_color_description --italics 6e6a86
fish_pager_color_selected_background
fish_pager_color_selected_prefix
fish_pager_color_selected_completion --bold e0def4
fish_pager_color_selected_description --bold 908caa
fish_pager_color_secondary_background
fish_pager_color_secondary_prefix
fish_pager_color_secondary_completion
fish_pager_color_secondary_description
