# https://fishshell.com/docs/current/interactive.html#syntax-highlighting-variables
fish_color_normal 575279
fish_color_command d7827e
fish_color_keyword d7827e
fish_color_quote ea9d34
fish_color_redirection
fish_color_end 56949f
fish_color_error b4637a
fish_color_param 907aa9
fish_color_valid_path
fish_color_option --italics d7827e
fish_color_comment --italics
fish_color_selection
fish_color_operator ea9d34
fish_color_escape 9893a5
fish_color_autosuggestion cecacd
fish_color_cwd --bold --dim
fish_color_cwd_root --bold --dim
fish_color_user ea9d34
fish_color_host 286983
fish_color_host_remote --reverse
fish_color_status b4637a
fish_color_cancel --dim
fish_color_search_match --background f2e9e1
fish_color_history_current --bold

# https://fishshell.com/docs/current/interactive.html#pager-color-variables
fish_pager_color_progress d7827e
fish_pager_color_background f2e9e1
fish_pager_color_prefix
fish_pager_color_completion 797593
fish_pager_color_description --italics 9893a5
fish_pager_color_selected_background
fish_pager_color_selected_prefix
fish_pager_color_selected_completion --bold 575279
fish_pager_color_selected_description --bold 797593
fish_pager_color_secondary_background
fish_pager_color_secondary_prefix
fish_pager_color_secondary_completion
fish_pager_color_secondary_description
