# name: Rosé Pine
# upstream: https://codeberg.org/dnkl/foot/src/branch/master/themes/rose-pine
#
# All natural pine, faux fur and a bit of soho vibes for the classy minimalist

[main]
initial-color-theme=dark

[colors-dark]
background=191724
foreground=e0def4
cursor=191724 e0def4

# regular colors (color palette 30-37)
regular0=191724         # black (Overlay)
regular1=eb6f92         # red (Love)
regular2=9ccfd8         # green (Foam)
regular3=f6c177         # yellow (Gold)
regular4=31748f         # blue (Pine)
regular5=c4a7e7         # magenta (Iris)
regular6=ebbcba         # cyan (Rose)
regular7=e0def4         # white (Text)

# bright colors (color palette 40-47)
bright0=4c4a57          # bright black (lighter Overlay)
bright1=ffa2c5          # bright red (lighter Love)
bright2=cfffff          # bright green (lighter Foam)
bright3=fff4aa          # bright yellow (lighter Gold)
bright4=64a7c2          # bright blue (lighter Pine)
bright5=f7daff          # bright magenta (lighter Iris)
bright6=ffefed          # bright cyan (lighter Rose)
bright7=ffffff          # bright white (lighter Text)

flash=f6c177            # yellow (Gold)

