# name: Rosé Pine Dawn
# upstream: https://codeberg.org/dnkl/foot/src/branch/master/themes/rose-pine-dawn
#
# All natural pine, faux fur and a bit of soho vibes for the classy minimalist

[main]
initial-color-theme=light

[colors-light]
background=faf4ed
foreground=575279
cursor=faf4ed 575279

# regular colors (color palette 30-37)
regular0=f2e9e1     # black (Overlay)
regular1=b4637a     # red (Love)
regular2=56949f     # green (Foam)
regular3=ea9d34     # yellow (Gold)
regular4=286983     # blue (Pine)
regular5=907aa9     # magenta (Iris)
regular6=d7827e     # cyan (Rose)
regular7=575279     # white (Text)



