# name: Rosé Pine Moon
# upstream: https://codeberg.org/dnkl/foot/src/branch/master/themes/rose-pine-moon
#
# All natural pine, faux fur and a bit of soho vibes for the classy minimalist

[main]
initial-color-theme=dark

[colors-dark]
background=232136
foreground=e0def4
cursor=232136 e0def4

# regular colors (color palette 30-37)
regular0=393552     # black (Overlay)
regular1=eb6f92     # red (Love)
regular2=9ccfd8     # green (Foam)
regular3=f6c177     # yellow (Gold)
regular4=3e8fb0     # blue (Pine)
regular5=c4a7e7     # magenta (Iris)
regular6=ea9a97     # cyan (Rose)
regular7=e0def4     # white (Text)

# bright colors (color palette 40-47)
bright0=6c6885      # bright black (lighter Overlay)
bright1=ffa2c5      # bright red (lighter Love)
bright2=cfffff      # bright green (lighter Foam)
bright3=fff4aa      # bright yellow (lighter Gold)
bright4=71c2e3      # bright blue (lighter Pine)
bright5=f7daff      # bright magenta (lighter Iris)
bright6=ffcdca      # bright cyan (lighter Rose)
bright7=ffffff      # bright white (lighter Text)

flash=f6c177        # yellow (Gold)

