# name: Rosé Pine Dawn
# upstream: https://codeberg.org/dnkl/foot/src/branch/master/themes/rose-pine-dawn
#
# All natural pine, faux fur and a bit of soho vibes for the classy minimalist

[main]
initial-color-theme=light

[colors-light]
background=faf4ed
foreground=575279
cursor=faf4ed 575279

# regular colors (color palette 30-37)
regular0=f2e9e1     # black (Overlay)
regular1=b4637a     # red (Love)
regular2=56949f     # green (Foam)
regular3=ea9d34     # yellow (Gold)
regular4=286983     # blue (Pine)
regular5=907aa9     # magenta (Iris)
regular6=d7827e     # cyan (Rose)
regular7=575279     # white (Text)

# bright colors (color palette 40-47)
bright0=bfb6ae      # bright black (darker Overlay)
bright1=813047      # bright red (darker Love)
bright2=23616c      # bright green (darker Foam)
bright3=b76a01      # bright yellow (darker Gold)
bright4=003650      # bright blue (darker Pine)
bright5=5d4776      # bright magenta (darker Iris)
bright6=a44f4b      # bright cyan (darker Rose)
bright7=241f46      # bright white (darker Text)

flash=ea9d34        # yellow (Gold)

